/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import extras.MyColor;
import extras.MyFormater;
import extras.Validacion;
import java.awt.event.KeyEvent;
import view.sales.FrmCobrar2;

public class FrmEfectivo extends javax.swing.JInternalFrame {

    public static boolean cobrar = true;

    public FrmEfectivo() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEfectivo1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtPagoCon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lblCambio = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();

        setBorder(null);

        panelEfectivo1.setBackground(new java.awt.Color(255, 255, 255));
        panelEfectivo1.setPreferredSize(new java.awt.Dimension(482, 211));

        jLabel9.setForeground(new MyColor().COLOR_JLABEL_PRIMARY);
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Pagó con:");

        txtPagoCon.setForeground(new MyColor().COLOR_FOCUS_TEXTFIELD);
        txtPagoCon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtPagoCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPagoConKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPagoConKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPagoConKeyTyped(evt);
            }
        });

        jLabel10.setForeground(new MyColor().COLOR_JLABEL_PRIMARY);
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Su cambio:");

        lblCambio.setForeground(new MyColor().COLOR_JLABEL_PRIMARY);
        lblCambio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCambio.setText("$0.00");

        lblError.setForeground(new java.awt.Color(255, 102, 0));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout panelEfectivo1Layout = new javax.swing.GroupLayout(panelEfectivo1);
        panelEfectivo1.setLayout(panelEfectivo1Layout);
        panelEfectivo1Layout.setHorizontalGroup(
            panelEfectivo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEfectivo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEfectivo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelEfectivo1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelEfectivo1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPagoCon, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 113, Short.MAX_VALUE))))
        );
        panelEfectivo1Layout.setVerticalGroup(
            panelEfectivo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEfectivo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEfectivo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPagoCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEfectivo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEfectivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelEfectivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPagoConKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagoConKeyPressed
        
    }//GEN-LAST:event_txtPagoConKeyPressed

    private void txtPagoConKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagoConKeyReleased
        evaluarMontoPago();
    }//GEN-LAST:event_txtPagoConKeyReleased

    private void txtPagoConKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagoConKeyTyped
        Validacion.decimales(evt, txtPagoCon);
    }//GEN-LAST:event_txtPagoConKeyTyped

    public static void evaluarMontoPago() {
        double cambio = pagoCon() - importeTotal();
        if (pagoCon() < importeTotal()) {
            lblError.setText("El efectivo ingresado es menor que total a cobrar. Verifique");
            lblCambio.setText("$0.00");
            cobrar = false;
            view.FrmMain.displayMessage(pagoCon() + " - " + importeTotal() + " = " + cambio);
        } else {
            cobrar = true;
            lblError.setText("");
            lblCambio.setText(MyFormater.formato(cambio));
            view.FrmMain.displayMessage(pagoCon() + " - " + importeTotal() + " = " + cambio);
        }

    }

    public static Double pagoCon() {
        Double pagocon = 0d;
        if (txtPagoCon.getText().equals("$") || txtPagoCon.getText().equals("")) {
            
        }else{
            String pago = txtPagoCon.getText();
            pago = pago.replace("$", "");
            pago = pago.replace(",", "");
            pagocon = Double.parseDouble(pago);
        }
        return pagocon;
    }

    public static Double importeTotal() {
        String imp = MyFormater.formato(FrmCobrar2.importeM);
        imp = imp.replace("$", "");
        imp = imp.replace(",", "");
        return Double.parseDouble(imp);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel lblCambio;
    public static javax.swing.JLabel lblError;
    private javax.swing.JPanel panelEfectivo1;
    public static javax.swing.JTextField txtPagoCon;
    // End of variables declaration//GEN-END:variables
}
