package view;

import controller.ControllerEmploye;
import extras.Conexion;
import extras.LongTask;
import extras.MyColor;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import model.ModelEmploye;
import extras.AES;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.Timer;

public class FrmLogin extends JFrame {

    private Conexion mysql = new Conexion();
    private Connection cn = mysql.getConnection();

    public final static int ONE_SECOND = 1000;

    private Timer timer;
    private LongTask task;
    FrmMain finicio;
    private boolean listo = false;

    ModelEmploye empleado;

    //ControllerLogin init;
    public FrmLogin() {
        initComponents();
        setLocationRelativeTo(null);
        progressBar.setVisible(false);
        lblCargando.setVisible(false);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/logo_muebleria.jpg")).getImage());
        lblRestablecerAhora.setVisible(false);
        //task = new LongTask(finicio.getComponentCount());
        task = new LongTask(200);
        //create a timer and a task
        timer = new Timer(ONE_SECOND, new TimerListener());
        // finicio = new FrmMain();
        //TITLE LOGIN
        titleLogin.setFont(new Font("Tahoma", Font.PLAIN, 12)); // Puede ajustar la fuente y el tamaño según sea necesario
        titleLogin.setPreferredSize(new Dimension(100, 50)); // Puede establecer las dimensiones preferidas del JLabel
        titleLogin.setLineWrap(true); // Esto permite que el texto se ajuste automáticamente a la longitud del JLabel
        titleLogin.setWrapStyleWord(true); // Esto evita que el texto se corte en medio de una palabra
    }

    int m = 0;

    class TimerListener implements ActionListener {

        public void actionPerformed(ActionEvent evt) {
            progressBar.setValue(task.getCurrent());
            m++;
            if (m == 1) {
                lblCargando.setText("Cargando.");
            }
            if (m == 2) {
                lblCargando.setText("Cargando..");
            }
            if (m == 3) {
                lblCargando.setText("Cargando...");
                m = 0;
            }

            if (task.done()) {
                //listo = true;
                lblCargando.setText("¡Listo!");
                iniciar();
            }
        }
    }

    private void login() {
        if (this.txtUsuario.getText().equals("") && this.txtPassword.getText().equals("")) {
            //JOptionPane.showMessageDialog(null, "Ingrese contraseña", "Acceso al sistema", JOptionPane.ERROR_MESSAGE);
            lblCargando.setVisible(true);
            lblCargando.setText("No tiene acceso al sistema.");
            this.txtUsuario.requestFocus();
        } else {
            if (this.txtUsuario.getText().equals("")) {
                //JOptionPane.showMessageDialog(null, "Ingrese contraseña", "Acceso al sistema", JOptionPane.ERROR_MESSAGE);
                lblCargando.setVisible(true);
                lblCargando.setText("Ingrese usuario o email");
                this.txtUsuario.requestFocus();
            } else {
                if (this.txtPassword.getText().equals("")) {
                    //JOptionPane.showMessageDialog(null, "Ingrese contraseña", "Acceso al sistema", JOptionPane.ERROR_MESSAGE);
                    lblCargando.setVisible(true);
                    lblCargando.setText("Ingrese contraseña");
                    this.txtPassword.requestFocus();
                } else {
                    ingresar(this.txtUsuario.getText(), this.txtPassword.getText());
                }
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        titleLogin = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        txtUsuario = new app.bolivia.swing.JCTextField();
        lblUsuario = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtPassword = new jpass.JRPasswordField();
        lblPassword = new javax.swing.JLabel();
        lblOlvideMiContraseña = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnIngresarLogin = new principal.MaterialButton();
        btnSalirLogin = new principal.MaterialButton();
        lblCargando = new javax.swing.JTextArea();
        lblRestablecerAhora = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mueblería Dinora - Acceso al sistema");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_muebleria_3.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 120));

        jPanel2.setBackground(new java.awt.Color(31, 25, 26));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLogin.setEditable(false);
        titleLogin.setBackground(new java.awt.Color(31, 25, 26));
        titleLogin.setColumns(2);
        titleLogin.setForeground(new java.awt.Color(135, 65, 155));
        titleLogin.setRows(5);
        titleLogin.setText("Por favor ingrese su usuario y contraseña para acceder\nal sistema");
        jPanel2.add(titleLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 300, 30));

        jPanel3.setBackground(new java.awt.Color(31, 25, 26));
        jPanel3.setMinimumSize(new java.awt.Dimension(330, 80));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setBorder(null);
        txtUsuario.setForeground(new java.awt.Color(135, 65, 155));
        txtUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUsuario.setPlaceholder("USUARIO O EMAIL");
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyReleased(evt);
            }
        });
        jPanel3.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 240, 30));

        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/campo-usuario.png"))); // NOI18N
        jPanel3.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 310, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 360, 70));

        jPanel4.setBackground(new java.awt.Color(31, 25, 26));
        jPanel4.setMinimumSize(new java.awt.Dimension(326, 80));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPassword.setBorder(null);
        txtPassword.setForeground(new java.awt.Color(135, 65, 155));
        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPassword.setPlaceholder("CONTRASEÑA");
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });
        jPanel4.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 240, 30));

        lblPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/campo-contrasena.png"))); // NOI18N
        jPanel4.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 360, 70));

        lblOlvideMiContraseña.setForeground(new java.awt.Color(135, 65, 155));
        lblOlvideMiContraseña.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOlvideMiContraseña.setText("Olvidé mi contraseña");
        lblOlvideMiContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOlvideMiContraseñaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOlvideMiContraseñaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOlvideMiContraseñaMouseExited(evt);
            }
        });
        jPanel2.add(lblOlvideMiContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 300, 20));

        jPanel6.setBackground(new java.awt.Color(31, 25, 26));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIngresarLogin.setBackground(new MyColor().COLOR_BUTTON);
        btnIngresarLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarLogin.setText("ingresar");
        btnIngresarLogin.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnIngresarLogin.setMaximumSize(new java.awt.Dimension(58, 25));
        btnIngresarLogin.setMinimumSize(new java.awt.Dimension(58, 25));
        btnIngresarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarLoginActionPerformed(evt);
            }
        });
        jPanel6.add(btnIngresarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 130, 40));

        btnSalirLogin.setBackground(new MyColor().COLOR_BUTTON);
        btnSalirLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnSalirLogin.setText("salir");
        btnSalirLogin.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnSalirLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirLoginActionPerformed(evt);
            }
        });
        jPanel6.add(btnSalirLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 140, 40));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 350, 60));

        lblCargando.setEditable(false);
        lblCargando.setBackground(new java.awt.Color(31, 25, 26));
        lblCargando.setColumns(10);
        lblCargando.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCargando.setForeground(new java.awt.Color(135, 65, 155));
        lblCargando.setRows(5);
        lblCargando.setFocusable(false);
        jPanel2.add(lblCargando, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 300, 40));

        lblRestablecerAhora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRestablecerAhora.setForeground(MyColor.COLOR_JLABEL_PRIMARY);
        lblRestablecerAhora.setText("Restablécela ahora");
        lblRestablecerAhora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRestablecerAhoraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRestablecerAhoraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRestablecerAhoraMouseExited(evt);
            }
        });
        jPanel2.add(lblRestablecerAhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 365, 80));

        progressBar.setBackground(new MyColor().COLOR_JLABEL_PRIMARY);
        progressBar.setForeground(new java.awt.Color(175, 0, 215));
        progressBar.setStringPainted(true);
        jPanel2.add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 300, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 330, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresar(String user, String password) {
        System.out.println("INGRESANDO");
        try {
            ControllerEmploye func = new ControllerEmploye();
            boolean band = func.validar(user, password);

            if (band) {
                System.out.println("BANDERA");
                empleado = func.getWorker(user, password);
                if (empleado.getInactivo() == 1) {
                    JOptionPane.showMessageDialog(this, "El trabajador ya no pertenece a la empresa", "Información", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                lblCargando.setVisible(true);
                progressBar.setVisible(true);
                task.go();
                timer.start();
                System.out.println("INICIANDO...");
            } else {
                lblCargando.setVisible(true);
                boolean r = new ControllerEmploye().perteneceAdministrador(user);
                if (r) {
                    lblCargando.setText("La cuenta o la contraseña es incorrecta.\nSi no recuerdas la cuenta.");
                    lblRestablecerAhora.setVisible(true);
                } else {
                    lblRestablecerAhora.setVisible(false);
                    lblCargando.setText("La cuenta o la contraseña es incorrecta.");
                }
            }
        } catch (Exception e) {
        }
    }

    private void iniciar() {
        finicio = new FrmMain();
        finicio.IdempleadoU = empleado.getIdempleado();
        finicio.btnUsuario.setText(empleado.getNombre());
        finicio.setVisible(true);
        //MENSAJE DE BIENVENIDA
        finicio.beep = false;
        finicio.notificar("Bienvenido " + empleado.getNombre());

        if (empleado.getPrivilegio() != 1) {
            finicio.btnClientesH.setEnabled(false);
            finicio.btnProductosH.setEnabled(false);
            finicio.btnInventarioH.setEnabled(false);
            finicio.btnConfiguracionH.setEnabled(false);
            finicio.btnCorte.setEnabled(false);
        }
        timer.stop();
        dispose();
    }


    private void lblOlvideMiContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOlvideMiContraseñaMouseClicked
        JOptionPane.showMessageDialog(this, "Si olvidó su contraseña , por favor pídale a su supervisor que restablezca su contraseña desde el apartado de Configuración / Cajeros", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_lblOlvideMiContraseñaMouseClicked

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void lblOlvideMiContraseñaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOlvideMiContraseñaMouseEntered
        lblOlvideMiContraseña.setFont(new java.awt.Font("Tahoma", 1, 12));
    }//GEN-LAST:event_lblOlvideMiContraseñaMouseEntered

    private void lblOlvideMiContraseñaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOlvideMiContraseñaMouseExited
        lblOlvideMiContraseña.setFont(new java.awt.Font("Tahoma", 1, 11));
    }//GEN-LAST:event_lblOlvideMiContraseñaMouseExited

    private void btnSalirLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirLoginActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirLoginActionPerformed

    private void txtUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyReleased
        lblCargando.setText("");
    }//GEN-LAST:event_txtUsuarioKeyReleased

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        lblCargando.setText("");
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void lblRestablecerAhoraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRestablecerAhoraMouseEntered
        lblRestablecerAhora.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblRestablecerAhoraMouseEntered

    private void lblRestablecerAhoraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRestablecerAhoraMouseExited
        lblRestablecerAhora.setForeground(MyColor.COLOR_JLABEL_PRIMARY);
    }//GEN-LAST:event_lblRestablecerAhoraMouseExited

    private void lblRestablecerAhoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRestablecerAhoraMouseClicked
        frmEnviarCorreo enviar = new frmEnviarCorreo(this, true);
        enviar.setVisible(true);
    }//GEN-LAST:event_lblRestablecerAhoraMouseClicked

    private void btnIngresarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarLoginActionPerformed
        login();
        descifrar();
    }//GEN-LAST:event_btnIngresarLoginActionPerformed

    public void descifrar() {
        PreparedStatement stmt;
        try {
            stmt = cn.prepareStatement("select * from empleado");
            ResultSet rs = stmt.executeQuery();
            String pass = "";
            String user = "";

            while (rs.next()) {
                pass = AES.decrypt(rs.getString("password"));
                user = rs.getString("usuario");
                System.out.println("DNI: " + user + " PASS: " + pass);
            }
        } catch (SQLException ex) {
            //ex.printStackTrace();(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            //ex.printStackTrace();(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */

    /*
    public static void main(String args[]) {
        //* Set the Nimbus look and feel 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.ex.printStackTrace();(FrmLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.ex.printStackTrace();(FrmLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.ex.printStackTrace();(FrmLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.ex.printStackTrace();(FrmLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ControllerLogin init = new ControllerLogin();                
                //new FrmLogin().setVisible(true);
                init.inicializar();
                
            }
        });
    }
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public principal.MaterialButton btnIngresarLogin;
    public principal.MaterialButton btnSalirLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea lblCargando;
    public javax.swing.JLabel lblOlvideMiContraseña;
    private javax.swing.JLabel lblPassword;
    public javax.swing.JLabel lblRestablecerAhora;
    private javax.swing.JLabel lblUsuario;
    public javax.swing.JProgressBar progressBar;
    private javax.swing.JTextArea titleLogin;
    public static jpass.JRPasswordField txtPassword;
    public static app.bolivia.swing.JCTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
