/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.clients;

import model.ModelMovClient;
import model.ModelPaymet;
import controller.ControllerMovClient;
import extras.MyColor;
import extras.MyFormater;
import extras.Validacion;
import controller.ControllerTicket;
import controller.ControllerClient;
import controller.ControllerPayment;
import static view.FrmMain.vaciarListaCreditos;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import view.FrmMain;

/**
 *
 * @author Developer
 */
public class FrmAbono2 extends javax.swing.JDialog {

    public static int IDCLIENTE = 0;
    public static int IDEMPLEADO = 0;
    public static String nombreCliente = "";

    public FrmAbono2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        this.txtCantidadAbono.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnAceptarAbono = new principal.MaterialButton();
        btnCancelarAbono = new principal.MaterialButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCantidadAbono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new MyColor().COLOR_BACKGROUND_BLACK);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ACCIONES");

        btnAceptarAbono.setBackground(new MyColor().COLOR_BUTTON);
        btnAceptarAbono.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptarAbono.setText("Aceptar");
        btnAceptarAbono.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnAceptarAbono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarAbonoActionPerformed(evt);
            }
        });

        btnCancelarAbono.setBackground(new MyColor().COLOR_BUTTON);
        btnCancelarAbono.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarAbono.setText("Cancelar");
        btnCancelarAbono.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnCancelarAbono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAbonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAceptarAbono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelarAbono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btnAceptarAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelarAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new MyColor().COLOR_JLABEL_PRIMARY);
        jLabel1.setText("ABONO");

        txtCantidadAbono.setForeground(new MyColor().COLOR_FOCUS_TEXTFIELD);
        txtCantidadAbono.setText("0.00");
        txtCantidadAbono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadAbonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadAbonoKeyTyped(evt);
            }
        });

        jLabel3.setForeground(new MyColor().COLOR_JLABEL_PRIMARY);
        jLabel3.setText("Monto a Abonar:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtCantidadAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarAbonoActionPerformed
        if (txtCantidadAbono.getText().equals("") || txtCantidadAbono.getText().equals("0.00") || txtCantidadAbono.getText().equals("0")) {
            view.FrmMain.notificar("No es posible abonar " + txtCantidadAbono.getText());
        } else {
            ingresarAbono();
        }
    }//GEN-LAST:event_btnAceptarAbonoActionPerformed

    private void btnCancelarAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAbonoActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarAbonoActionPerformed

    private void txtCantidadAbonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadAbonoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtCantidadAbono.getText().equals("") || txtCantidadAbono.getText().equals("0.00") || txtCantidadAbono.getText().equals("0")) {
                view.FrmMain.notificar("No es posible abonar " + txtCantidadAbono.getText());
            } else {
                ingresarAbono();
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            dispose();
        }
    }//GEN-LAST:event_txtCantidadAbonoKeyPressed

    private void txtCantidadAbonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadAbonoKeyTyped
        Validacion.decimales(evt, txtCantidadAbono);
    }//GEN-LAST:event_txtCantidadAbonoKeyTyped

    private void ingresarAbono() {
        if (!txtCantidadAbono.getText().equals("")) {
            Double limiteCredito = new ControllerClient().limiteCreditoCliente(String.valueOf(IDCLIENTE));
            Double abono = Double.parseDouble(txtCantidadAbono.getText());
            Double SALDO_ACTUAL_USUARIO = new ControllerClient().saldoActualCliente(String.valueOf(IDCLIENTE));
            if (abono > SALDO_ACTUAL_USUARIO) {
                int opcion = JOptionPane.showConfirmDialog(null, "Estas abonando $" + abono + " que es mayor que el saldo de $" + SALDO_ACTUAL_USUARIO + "\n"
                        + "¿Desea liquidar el adeudo del cliente?", "Confirmar", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (opcion == 0) {
                    liquidarCuenta();
                }
            } else {
                abonar(abono);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Verifique su monto que desea abonar");
        }
    }

    private void abonar(Double monto) {
        ModelPaymet pago = new ModelPaymet();
        ControllerPayment func = new ControllerPayment();
        pago.setIdcliente(IDCLIENTE);
        pago.setIdempleado(IDEMPLEADO);
        pago.setMonto(monto);
        if (func.insertar(pago)) {
            //ABONAR DEUDO CLIENTE
            try {
                extras.Impresora.imprimirAbonoCuentaCliente(FrmMain.confiEncabezadoTicket, FrmMain.getNombreCliente(IDCLIENTE), String.valueOf(IDCLIENTE));
                view.FrmMain.beep = false;
                FrmMain.notificar(MyFormater.formato(monto) + " Abonados al cliente");
            } catch (PrinterException ex) {
                ex.printStackTrace();
            }
            view.FrmMain.mostrar("");
            view.FrmMain.lblSaldoActualCliente.setText(MyFormater.formato(new ControllerClient().saldoActualCliente(String.valueOf(IDCLIENTE))));

            //REGISTRAR MOVIMIETO CLIENTE
            ModelMovClient dtMovC = new ModelMovClient();
            ControllerMovClient funcMovC = new ControllerMovClient();

            dtMovC.setIdcliente(IDCLIENTE);
            dtMovC.setTipo(1); //El valor es 1 cuando es ABONO
            dtMovC.setMonto(monto);
            funcMovC.insertar(dtMovC);
            dispose();
        }
    }

    private void liquidarCuenta() {
        ModelPaymet dts = new ModelPaymet();
        ControllerPayment func = new ControllerPayment();

        //LIQUIDACIÓN DE CUENTA
        try {
            extras.Impresora.imprimirLiquidacionCuentaCliente(FrmMain.confiEncabezadoTicket, FrmMain.getNombreCliente(IDCLIENTE), String.valueOf(IDCLIENTE));
        } catch (PrinterException ex) {
            ex.printStackTrace();
        }

        dts.setIdcliente(IDCLIENTE);
        new ControllerTicket().liquidarTicketCliente(IDCLIENTE);
        if (func.eliminar(dts)) {
            FrmMain.cargarMeses("" + IDCLIENTE);
        }
        FrmMain.cargarMeses("" + IDCLIENTE);
        FrmMain.lblSaldoActualCliente.setText(MyFormater.formato(new ControllerClient().saldoActualCliente(String.valueOf(IDCLIENTE))));
        vaciarListaCreditos();
        FrmMain.mostrar(""); //PARA ACTUALIZAR SALDO ACTUAL EN EL LISTADO DE CLIENTES
        FrmMain.btnAbonarCliente.setEnabled(false);
        FrmMain.btnLiquidarAdeudo.setEnabled(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } catch (InstantiationException ex) {
            ex.printStackTrace();
        } catch (IllegalAccessException ex) {
            ex.printStackTrace();
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmAbono2 dialog = new FrmAbono2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private principal.MaterialButton btnAceptarAbono;
    private principal.MaterialButton btnCancelarAbono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCantidadAbono;
    // End of variables declaration//GEN-END:variables
}
