package view.clients;

import extras.EstiloTablaHeader;
import extras.EstiloTablaRenderer;
import extras.MyColor;
import extras.MyFormater;
import extras.MyScrollbarUI;
import controller.ControllerClient;
import controller.ControllerPayment;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import view.FrmMain;

public class FrmDetalleAbono2 extends javax.swing.JDialog {

    DefaultTableModel modelo;
    public static int Idcliente = 0;

    public FrmDetalleAbono2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.getVerticalScrollBar().setUI(new MyScrollbarUI());
        jScrollPane1.getHorizontalScrollBar().setUI(new MyScrollbarUI());

        dtDetalleAbono.getTableHeader().setDefaultRenderer(new EstiloTablaHeader());
        dtDetalleAbono.setDefaultRenderer(Object.class, new EstiloTablaRenderer());
    }

    public void mostrarAbonos(String buscar) {
        try {
            DefaultTableModel modelo;
            ControllerPayment func = new ControllerPayment();
            modelo = func.mostrar(buscar);

            dtDetalleAbono.setModel(modelo);
            ocultar_columnas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }

    }

    void ocultar_columnas() {
        dtDetalleAbono.getColumnModel().getColumn(0).setMaxWidth(1);
        dtDetalleAbono.getColumnModel().getColumn(0).setMinWidth(1);
        dtDetalleAbono.getColumnModel().getColumn(0).setPreferredWidth(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnEliminarAbono2 = new principal.MaterialButton();
        btnAceptarAbono2 = new principal.MaterialButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dtDetalleAbono = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(72, 31));
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new MyColor().COLOR_JLABEL_PRIMARY);
        jLabel3.setText("DETALLE ABONOS");

        jPanel6.setBackground(new MyColor().COLOR_BACKGROUND_BLACK);

        btnEliminarAbono2.setBackground(new MyColor().COLOR_BUTTON);
        btnEliminarAbono2.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarAbono2.setText("eliminar abono");
        btnEliminarAbono2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnEliminarAbono2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAbono2ActionPerformed(evt);
            }
        });

        btnAceptarAbono2.setBackground(new MyColor().COLOR_BUTTON);
        btnAceptarAbono2.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptarAbono2.setText("aceptar");
        btnAceptarAbono2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnAceptarAbono2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarAbono2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEliminarAbono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptarAbono2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarAbono2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptarAbono2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        dtDetalleAbono.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Monto", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dtDetalleAbono.setShowHorizontalLines(false);
        dtDetalleAbono.setShowVerticalLines(false);
        jScrollPane1.setViewportView(dtDetalleAbono);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarAbono2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAbono2ActionPerformed
        int filaSel = dtDetalleAbono.getSelectedRow();
        if (filaSel == -1) {
            JOptionPane.showMessageDialog(null, "Por favor seleccione un abono a eliminar");
        } else {
            int idPago = Integer.parseInt(dtDetalleAbono.getValueAt(filaSel, 0).toString());
            ControllerPayment funPago = new ControllerPayment();

            int opcion = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea eliminar este Abono?", "Confirmar", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (opcion == 0) {
                if(funPago.eliminarAbono(idPago)){
                    mostrarAbonos("");
                    FrmMain.mostrar("");
                    view.FrmMain.lblSaldoActualCliente.setText(MyFormater.formato(new ControllerClient().saldoActualCliente(String.valueOf(Idcliente))));
                    JOptionPane.showMessageDialog(null,"Abono eliminado");
                }
                
            }
        }
    }//GEN-LAST:event_btnEliminarAbono2ActionPerformed

    private void btnAceptarAbono2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarAbono2ActionPerformed
        dispose();
    }//GEN-LAST:event_btnAceptarAbono2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmDetalleAbono2 dialog = new FrmDetalleAbono2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private principal.MaterialButton btnAceptarAbono2;
    private principal.MaterialButton btnEliminarAbono2;
    private javax.swing.JTable dtDetalleAbono;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
